[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
command = "tuigreet --time --asterisks --theme border=#7cafc2;container=#282828;text=#d8d8d8;prompt=#b8b8b8;input=#d8d8d8;greet=#f7ca88;time=#ba8baf;action=#86c1b9;button=#dc9656 --cmd sway"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greetd"
